theme: architect

title: Jezper.co
author: Jezper
email: jezper@jezper.co
description: > # this means to ignore newlines until "baseurl:"
  Unsolicited opinions about technology, design and everything else.

# social links
twitter_username: jezperse
github_username:  jezper

show_excerpts: true # set to false to remove excerpts on the homepage
